<a href="https://colab.research.google.com/github/SpencerLugalia/Spencer-1/blob/main/Lesson_8_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
arr_sample = np.array([4,6,7])

In [4]:
print(arr_sample)

[4 6 7]


In [5]:
type(arr_sample)

numpy.ndarray

In [6]:
#creating a 1 dimensional array

x= np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
#creating a 2 dimensional array

arr2d =np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [9]:
#creating a 3D array(This is 2D however run .shape & .ndim to confirm)

arr3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3d)
type(arr3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [15]:
x.shape

(3,)

In [16]:
.ndim

1

In [12]:
!pip install numpy

In [18]:
#creating a 3D array

ar3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3d)
type(ar3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


numpy.ndarray

In [19]:
ar3d.shape

(1, 3, 3)

In [20]:
ar3d.ndim

3

In [29]:
#3d with 2 Matrixes

r3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(r3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
r3d.shape

(2, 2, 3)

In [31]:
r3d.ndim

3

numpy converts to one data type

###Arithmetic Operations

In [32]:
no_array = np.array([5000, 7000, 20000])

In [33]:
no_array*1.23

array([ 6150.,  8610., 24600.])

In [34]:
#multiply list by 3
no_list = [3,0,7]

In [35]:
no_list *3

[3, 0, 7, 3, 0, 7, 3, 0, 7]

In [36]:
#adding
no_array +1000

array([ 6000,  8000, 21000])

In [37]:
no_list + 200

TypeError: can only concatenate list (not "int") to list

In [41]:
no_list1 =np.array(no_list)
no_list1

array([3, 0, 7])

In [42]:
no_list1 +200

array([203, 200, 207])

#####Scalar Math

In [43]:
#scalar math (adds one element)
np.add(no_list1, 67)

array([70, 67, 74])

#####Vector Math

In [44]:
#np.add(arr1,arr2)

arr1 = np.array([1,2,5])

In [47]:
arr2 = np.array([4,6,2])

In [48]:
arr1 + arr2

array([5, 8, 7])

In [49]:
#round off

trx = np.array([1.78, 8.654,7.453])
trx.round()

array([2., 9., 7.])

In [50]:
trx = np.array([675345, 86546,87537])
trx.round(-2)

array([675300,  86500,  87500])

In [51]:
#broadcast
rr33 = np.array([12,17])
rr44 = np.array([6,7])
rr55 = np.array([3,6,8])

In [52]:
rr33*rr44

array([ 72, 119])

In [54]:
rr44*rr55

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [55]:
#list of heights in inches

list_h_iinches = ([65, 98, 76, 54, 30, 90])

#convert to meters

c_rate = 0.3048

In [56]:
#convert inches to metres

array_h_inches = np.array(list_h_iinches)

In [57]:
array_m = array_h_inches * c_rate
array_m

array([19.812 , 29.8704, 23.1648, 16.4592,  9.144 , 27.432 ])